AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Micronaut API - micronaut.lambda.graal::micronaut-lambda-graal
Globals:
  Api:
    EndpointConfiguration: REGIONAL
  Function:
    Timeout: 60
Resources:
  TodoService:
    Type: AWS::Serverless::Function
    Properties:
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: build/app.zip
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          MICRONAUT_ENVIRONMENTS: "prod"
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MyServiceApi
