AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Micronaut API - micronaut.lambda.graal::micronaut-lambda-graal
Globals:
  Api:
    EndpointConfiguration: REGIONAL
  Function:
    Timeout: 60
Resources:
  TodoService:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: build/libs/hello-world-0.1-all.jar
      Handler: de.sturmm.todo.Application::handleRequest
      Runtime: java8
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          MICRONAUT_ENVIRONMENTS: "prod"

Outputs:
  MyServiceApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MyServiceApi
